# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-node-database-url
  namespace: demo-app
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@cnpg-minimal-rw.postgres.svc.cluster.local:5432/postgres
